### ISSUE TITLE
[BUG] Node Graph API is not using getBackendSrv/Proxy resulting access issues and CORS issues

### ISSUE THREAD

**Issue by jtorkkel** [hoptical/nodegraph-api-plugin#12]
**Describe the bug**
Node Graph plugin is not using Grafana recommended getBackendSrv/proxy . This result that all queries done by plugin are actually originating from the machine running the Browser. For example calling localhost calls the calling machine localhost, not localhost in machine where Grafana is running.

This leads to 
- access issues if URL the plugin is accessing is whitelisted, for example VPN access
- CORS issues, Need to have CORS headers in response, Browser still might block quests

**Expected behavior**
Using getBackendSrv which proxy request through grafana server.

Extract from https://grafana.com/tutorials/build-a-data-source-plugin/
While you can use something like [axios](https://github.com/axios/axios) or the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to make requests, we recommend using the [getBackendSrv](https://grafana.com/docs/grafana/latest/packages_api/runtime/getbackendsrv/) function from the [grafana/runtime](https://grafana.com/docs/grafana/latest/packages_api/runtime/) package.

The main advantage of getBackendSrv is that it proxies requests through the Grafana server rather making the request from the browser. This is strongly recommended when making authenticated requests to an external API. For more information on authenticating external requests, refer to [Add authentication for data source plugins](https://grafana.com/docs/grafana/latest/developers/plugins/add-authentication-for-data-source-plugins/).

**Comment by hoptical** [comment]
@jtorkkel thanks for opening this issue.
You're right and I already announced it in the [roadmap](https://github.com/hoptical/nodegraph-api-plugin#roadmap).

I will soonly fix this issue via getBackendSrv or converting the plugin to a [backend](https://grafana.com/tutorials/build-a-data-source-backend-plugin/) one.
