### ISSUE TITLE
remove "arc__" text from legend

### ISSUE THREAD

**Issue by jtorkkel** [hoptical/nodegraph-api-plugin#15]
At the moment in Node Graph all legends contain text prefix "arc__" like "arc__failed" or "arc_passed".

**Describe the solution you'd like**
I would like to see legend not including "arc__" test. Grafana own AWS Node Graph and infinity datasource does not show "arc__" text when graph visualized.

**Comment by hoptical** [comment]
Currently, there is no specification about "arc__" legends in the [node graph documentation](https://grafana.com/docs/grafana/latest/visualizations/node-graph/#node-parameters). 
This will force us to search in the node graph source files like [this one](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/nodeGraph/Legend.tsx). But I couldn't find anything there too. It just handles the color and its mode, not the legend.
