### ISSUE TITLE
Change the direction of the connecting wire

### ISSUE THREAD

**Issue by Ehsan-joe** [hoptical/nodegraph-api-plugin#16]
**Hi developers, I really appreciate you developing this plugin.**
**My question is**
We just specify the starting point and the ending point, and NodeGraph will automatically draw it,But I have to specify the direction and position of the lines and the nodes.

I expected the result：
![expect](https://user-images.githubusercontent.com/78342666/160536760-b54a2283-4222-4d32-ba35-ef03285d5f40.png)

The result:
![Snipaste_2022-03-29_13-00-40](https://user-images.githubusercontent.com/78342666/160536800-4d3d7418-8d25-44a3-b10b-a7b0fd762f5c.png)

**Can I change the position and orientation of nodes and lines? What should I do?**

---------------------------------------------------------------------------------------------------------------------------------------------------
> My Data source,and other config
Data source : node graph api
Data: Use Django to send data to the Node Graph API

> My Data
![myData](https://user-images.githubusercontent.com/78342666/160537655-ce81428d-eacf-4261-974e-64a4d58995da.png)

>My Code
```python
import json

# Create your views here.
from django.http import HttpResponse
from django.db import connection
from datetime import date, datetime


class ComplexEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(obj, date):
            return obj.strftime('%Y-%m-%d')
        else:
            return json.JSONEncoder.default(self, obj)


def fetch_graph_fields(request):
    nodes_fields = [{"field_name": "id", "type": "string"},
                    {"field_name": "title", "type": "string"},
                    {"field_name": "mainStat", "type": "string"},
                    {"field_name": "arc__failed",
                     "type": "number", "color": "red"},
                    {"field_name": "arc__passed",
                     "type": "number", "color": "green"},
                    {"field_name": "detail__role",
                     "type": "string", "displayName": "Role"}]
    edges_fields = [
        {"field_name": "id", "type": "string"},
        {"field_name": "source", "type": "string"},
        {"field_name": "target", "type": "string"},
    ]
    result = {"nodes_fields": nodes_fields,
              "edges_fields": edges_fields}
    return HttpResponse(json.dumps(result))


def fetch_graph_data(request):
    sql = 'select * from jsonData'
    cursor = connection.cursor()
    cursor.execute(sql)

    nodeData = cursor.fetchone()

    nodes = []
    edges = []
    for i, node in zip(range(1, 38), nodeData):
        nodeDict = json.loads(node)
        nodes.append(nodeDict)
        if i == 37:
            continue
        data = {"id": "%s" % str(i),
                "source": "%s" % str(i),
                "target": "%s" % str(i + 1)}
        edges.append(data)

    result = {"nodes": nodes,
              "edges": edges}
    return HttpResponse(json.dumps(result))


def check_health(request):
    return HttpResponse("API is working well!")
```

**Comment by hoptical** [comment]
Hi @Ehsan-joe,
No, you won't be able to do this. This should be handled by [Node Graph Panel](https://grafana.com/docs/grafana/latest/visualizations/node-graph/), not this data source. 
BTW, at the moment, the panel does **not** support the orientation and position of the nodes and edges via the given data.

**Comment by Ehsan-joe** [comment]
well, thank you

**Comment by Ehsan-joe** [comment]
Excuse me, do you know if there is a plug-in that fits my situation

**Comment by hoptical** [comment]
You can try the [Diagram plugin ](https://grafana.com/grafana/plugins/jdbranham-diagram-panel/) which uses [Marmaid J](https://mermaid-js.github.io/mermaid/#/flowchart)s syntax. You've to transfer the data to this syntax in your app and then address it to the plugin to visualize it. (The plugin can take diagram definition via API too).

Another one is the [Flowcharting plugin](https://grafana.com/grafana/plugins/agenty-flowcharting-panel/) but I found it hard to take diagram definition via API in this one.

**Comment by Ehsan-joe** [comment]
I have tried the Diagram Plugin, Marmaid Js cannot change direction halfway,
Let me try this Flowcharting plugin.
Thank you very much!
