### ISSUE TITLE
config.displayName and config.unit

### ISSUE THREAD

**Issue by greyslater** [hoptical/nodegraph-api-plugin#4]
found your absolute great work after I tried my luck with a CSV Data Source
primary functions work with CSV but very early I reached the limitations so I needed to find another approach, and here I am :)

Is there possibility to add feature for config.unit and config.displayName in a future release?

this is an example from the TestData DB Query:

"name": "mainStat",
          "type": "number",
          "config": {
            "unit": "ms/t",
            "displayName": "Average response time"

**Comment by greyslater** [comment]
I'm not good at code but found out, that actually it takes displayName already for mainStat and secondaryStat very well

for arc__* if i provide color and displayName together it can't take both of them but I think it's because we write outputField.config for displayName over the color one and that "breaks" it

sure if we "merge" everything correct for outputField.config (color, displayName, unit) - this should work - i guess

**Comment by hoptical** [comment]
Sorry for the late answer. Unfortunately, I didn't get notifications of the issues. I will respond quickly from now on.

You can use `arc__*` and displayName together as it's appropriately working in this [API example](https://github.com/exaco/nodegraph-api-plugin/blob/master/example/api/python/run.py):
`
{"field_name": "arc__passed",
 "type": "number", "color": "green"},
{"field_name": "detail__role",
 "type": "string", "displayName": "Role"}]
`

`detail__*` works for nodes and can be visualized in **Grid Layout**(not in default layout).
But it doesn't work for edges. It's from the NodeGraph plugin itself and not this data source.
