### ISSUE TITLE
Using a mysql query with source & target

### ISSUE THREAD

**Issue by gavin20** [hoptical/nodegraph-api-plugin#5]
Hello,

Is it possible to utilize this plugin with a mysql query with source & target parameters? I tried, does not render. If possible, could you provide an example? Thanks

**Comment by hoptical** [comment]
Hi, sorry for the late answer. Unfortunately, I didn't get notifications of the issues. I will respond quickly from now on.

The query parameter doesn't work and you can't use any kind of query including MySQL there. API is The only way to use the data source as it's documented in the readme and example given [here](https://github.com/exaco/nodegraph-api-plugin/blob/master/example/api/python/run.py).
