### ISSUE TITLE
[Question] how to install and use the datasource plugin

### ISSUE THREAD

**Issue by shenlanse** [hoptical/nodegraph-api-plugin#7]
Hi, sorry to bother you and ask for some help. I have installed the datasource plugin and create new panel with 'Visualization- Node Graph' and 'Node Graph API datasource plugin', but I don't know how to set 'Query text' below the panel. Could you please give an example? Thanks.

**Comment by hoptical** [comment]
In node or edge? What did you expect? Explain more, please.
